# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',   url: 'about'}
- {name: 'Blog',   url: ''}
- {name: 'Research', url: 'research'}
- {name: 'Interactive', url: 'interactive'}
- {name: 'Archive', url: 'archive'}
- {name: 'Resumé', url: 'assets/pdf/Joseph-Wilson-CV.pdf', target: 'blank'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/jollywatt'}
# - {icon: 'twitter',    link: 'https://twitter.com/paululele'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/joseph-wilson-893153232/'}
- {icon: 'envelope',   link: 'mailto:jo.alex.w@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text

# comments via https://giscus.app/
giscus: yes

use-katex: yes

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Related:'