# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',   url: 'about'}
- {name: 'Writing', url: 'writing'}
- {name: 'Math One-liners', url: 'math-one-liners'}
- {name: 'Research', url: 'research'}
- {name: 'CV', url: 'assets/pdf/Joseph-Wilson-CV.pdf', target: 'blank'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/jollywatt'}
# - {icon: 'twitter',    link: 'https://twitter.com/paululele'}
# - {icon: 'linkedin',   link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope',   link: 'mailto:jo.alex.w@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'



sharing_button_prompt: 'Feel free to share!'

related_posts: 'Related:'